blank_issues_enabled: false
contact_links:
  - name: â“ Discussion Forum
    url: https://forums.swift.org/c/related-projects/argumentparser/60
    about: Questions about using Swift Argument Parser? Ask here!
